package templates

// GoDockerfile returns a Dockerfile for Go applications
func GoDockerfile(framework string) string {
	return `# Go Dockerfile - Generated by stackgen
# Multi-stage build for optimal image size

# Build stage
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Install dependencies
RUN apk add --no-cache git ca-certificates

# Copy go mod files
COPY go.mod go.sum* ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/server .

# Runtime stage
FROM alpine:3.19

WORKDIR /app

# Add non-root user for security
RUN adduser -D -g '' appuser
USER appuser

# Copy binary from builder
COPY --from=builder /app/server /app/server

EXPOSE 8080

CMD ["/app/server"]
`
}

// NodeDockerfile returns a Dockerfile for Node.js applications
func NodeDockerfile(framework string) string {
	switch framework {
	case "nextjs":
		return `# Next.js Dockerfile - Generated by stackgen
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable && pnpm i --frozen-lockfile; \
  else npm install; \
  fi

# Development stage
FROM base AS development
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
`
	default:
		return `# Node.js Dockerfile - Generated by stackgen
FROM node:20-alpine

WORKDIR /app

# Add non-root user for security
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source code
COPY --chown=nodejs:nodejs . .

USER nodejs

EXPOSE 3000

CMD ["node", "index.js"]
`
	}
}

// PythonDockerfile returns a Dockerfile for Python applications
func PythonDockerfile(framework string) string {
	switch framework {
	case "fastapi":
		return `# FastAPI Dockerfile - Generated by stackgen
FROM python:3.12-slim

WORKDIR /app

# Create non-root user
RUN useradd -m -u 1000 appuser

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY --chown=appuser:appuser . .

USER appuser

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
`
	case "django":
		return `# Django Dockerfile - Generated by stackgen
FROM python:3.12-slim

WORKDIR /app

# Create non-root user
RUN useradd -m -u 1000 appuser

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY --chown=appuser:appuser . .

USER appuser

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
`
	default:
		return `# Python Dockerfile - Generated by stackgen
FROM python:3.12-slim

WORKDIR /app

# Create non-root user
RUN useradd -m -u 1000 appuser

# Install dependencies
COPY requirements.txt* .
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

# Copy source code
COPY --chown=appuser:appuser . .

USER appuser

EXPOSE 8000

CMD ["python", "app.py"]
`
	}
}

// JavaDockerfile returns a Dockerfile for Java applications
func JavaDockerfile(framework string) string {
	switch framework {
	case "spring-boot":
		return `# Spring Boot Dockerfile - Generated by stackgen
# Multi-stage build

# Build stage
FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

# Copy Maven/Gradle files
COPY pom.xml* mvnw* ./
COPY .mvn* .mvn/
COPY build.gradle* gradlew* ./
COPY gradle* gradle/

# Download dependencies
RUN if [ -f mvnw ]; then ./mvnw dependency:go-offline; \
    elif [ -f gradlew ]; then ./gradlew dependencies; fi

# Copy source and build
COPY src ./src
RUN if [ -f mvnw ]; then ./mvnw package -DskipTests; \
    elif [ -f gradlew ]; then ./gradlew bootJar; fi

# Runtime stage
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Add non-root user
RUN addgroup -g 1001 -S spring && adduser -S spring -u 1001
USER spring

# Copy JAR from builder
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
`
	default:
		return `# Java Dockerfile - Generated by stackgen
FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Add non-root user
RUN addgroup -g 1001 -S java && adduser -S java -u 1001

# Copy source
COPY --chown=java:java . .

USER java

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
`
	}
}

// RustDockerfile returns a Dockerfile for Rust applications
func RustDockerfile(framework string) string {
	return `# Rust Dockerfile - Generated by stackgen
# Multi-stage build for minimal image size

# Build stage
FROM rust:1.75-alpine AS builder

WORKDIR /app

# Install musl for static linking
RUN apk add --no-cache musl-dev

# Create a new empty shell project
RUN USER=root cargo new --bin app
WORKDIR /app

# Copy manifests
COPY Cargo.toml Cargo.lock* ./

# Build dependencies (cached layer)
RUN cargo build --release && rm src/*.rs

# Copy source code
COPY src ./src

# Build application
RUN rm ./target/release/deps/app* && cargo build --release

# Runtime stage - scratch for minimal size
FROM alpine:3.19

WORKDIR /app

# Add non-root user
RUN adduser -D -g '' appuser
USER appuser

# Copy binary
COPY --from=builder /app/target/release/app /app/server

EXPOSE 8080

CMD ["/app/server"]
`
}

// CSharpDockerfile returns a Dockerfile for C#/.NET applications
func CSharpDockerfile(framework string) string {
	return `# .NET Dockerfile - Generated by stackgen
# Multi-stage build

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS builder

WORKDIR /app

# Copy project files
COPY *.csproj ./
RUN dotnet restore

# Copy source and build
COPY . ./
RUN dotnet publish -c Release -o out

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

WORKDIR /app

# Add non-root user
RUN adduser -D -g '' appuser
USER appuser

# Copy published app
COPY --from=builder /app/out .

EXPOSE 5000

ENTRYPOINT ["dotnet", "app.dll"]
`
}

// GitIgnore returns a .gitignore file for stackgen projects
func GitIgnore() string {
	return `# stackgen generated .gitignore

# Environment files with secrets
.env
.env.local
.env.*.local

# Docker volumes (if using bind mounts)
data/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Dependencies (language-specific)
node_modules/
vendor/
__pycache__/
*.pyc
target/
bin/
obj/
`
}
